name: Trigger auto deployment for se2

on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - main
    paths:
      - '**' # Triggers on any push to main. Can be refined to specific paths if needed.
      # - '.github/workflows/se2-AutoDeployTrigger-43a0966a-17cf-4b3b-a705-e5403fa3c3d6.yml' # Redundant if 'paths: - "**"' is used

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for requesting the OIDC JWT Token
      contents: read # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4 # Updated to v4

      - name: Azure Login
        # Using v1.4.0 for broader compatibility with specific client-id/tenant-id
        # Consider v2 if you face issues or want the absolute latest.
        uses: azure/login@v1.4.0
        with:
          client-id: ${{ secrets.SE2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SE2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SE2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry and deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          # Corrected parameter name for Dockerfile path
          dockerfilePath: Dockerfile # Assuming your Dockerfile is at the root of appSourcePath
          registryUrl: bookanddockbymalign.azurecr.io
          # REMOVED registryUsername and registryPassword
          # The azure/login step should provide authentication to ACR
          containerAppName: se2
          resourceGroup: se2-pw
          imageToBuild: bookanddockbymalign.azurecr.io/se2:${{ github.sha }}
          # Corrected parameter name for build arguments
          # Add actual build arguments if needed (e.g., "ENV_VAR_NAME=value")
          buildArguments: "" # No build arguments specified, keep empty if not needed